// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTqkqFCvebPagtpslPtdbLzHISiSjWF3A',
    appId: '1:1042017156089:web:1c7962eae856d5a62e5b28',
    messagingSenderId: '1042017156089',
    projectId: 'kickboxing-zezo1',
    authDomain: 'kickboxing-zezo1.firebaseapp.com',
    databaseURL: 'https://kickboxing-zezo1-default-rtdb.firebaseio.com',
    storageBucket: 'kickboxing-zezo1.appspot.com',
    measurementId: 'G-KXVYXKZTYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTPmxkAscG62DcR94zHRKwQOQ7h0fYlQ4',
    appId: '1:1042017156089:android:45b9e75d5b4297c82e5b28',
    messagingSenderId: '1042017156089',
    projectId: 'kickboxing-zezo1',
    databaseURL: 'https://kickboxing-zezo1-default-rtdb.firebaseio.com',
    storageBucket: 'kickboxing-zezo1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ZqwEDt-9hOefT7RmXJ0D8eS827XcZCM',
    appId: '1:1042017156089:ios:f26adeeb67f8936c2e5b28',
    messagingSenderId: '1042017156089',
    projectId: 'kickboxing-zezo1',
    databaseURL: 'https://kickboxing-zezo1-default-rtdb.firebaseio.com',
    storageBucket: 'kickboxing-zezo1.appspot.com',
    iosBundleId: 'com.examplee.readtoday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ZqwEDt-9hOefT7RmXJ0D8eS827XcZCM',
    appId: '1:1042017156089:ios:f26adeeb67f8936c2e5b28',
    messagingSenderId: '1042017156089',
    projectId: 'kickboxing-zezo1',
    databaseURL: 'https://kickboxing-zezo1-default-rtdb.firebaseio.com',
    storageBucket: 'kickboxing-zezo1.appspot.com',
    iosBundleId: 'com.examplee.readtoday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTqkqFCvebPagtpslPtdbLzHISiSjWF3A',
    appId: '1:1042017156089:web:663cdfc4cc297fa92e5b28',
    messagingSenderId: '1042017156089',
    projectId: 'kickboxing-zezo1',
    authDomain: 'kickboxing-zezo1.firebaseapp.com',
    databaseURL: 'https://kickboxing-zezo1-default-rtdb.firebaseio.com',
    storageBucket: 'kickboxing-zezo1.appspot.com',
    measurementId: 'G-4N3X7N93V2',
  );
}
